DELIMITER //
CREATE PROCEDURE SUM_PROC(IN start_value INTEGER, IN end_value INTEGER,OUT EVENSUM INTEGER,OUT ODDSUM INTEGER)
BEGIN
DECLARE COUNTER INTEGER DEFAULT 0;
  SET COUNTER = start_value;
  SET EVENSUM = 0;
  SET ODDSUM = 0;
  LOOP_LABEL : LOOP

    IF COUNTER > end_value THEN
      LEAVE LOOP_LABEL;
    END IF;
      
    IF (COUNTER mod 2) THEN
      SET ODDSUM = ODDSUM + COUNTER;
    ElSE
      SET EVENSUM = EVENSUM + COUNTER;
    END IF;

    SET COUNTER = COUNTER + 1;
    ITERATE LOOP_LABEL;

  END LOOP;
END;
//
DELIMITER ;


CALL SUM_PROC(1, 100, @EVENSUM, @ODDSUM);

SELECT @EVENSUM;

SELECT @ODDSUM;
