CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INTEGER,
    DEPARTMENT_NAME VARCHAR(20),
    NUM_OF_EMPLOYEES INTEGER,
    HEAD_NAME VARCHAR(20),
    MANAGERS INTEGER,
    WORKERS INTEGER,
    PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE POST
(
    DESIGNATION VARCHAR(20),
    NUM_OF_EMPLOYEES INTEGER,
    TOTAL_AMOUNT FLOAT,
    PRIMARY KEY (DESIGNATION)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INTEGER,
    DEPARTMENT_ID INTEGER,
    EMPLOYEE_NAME VARCHAR(20),
    POST_NUMBER INTEGER,
    SALARY FLOAT,
    DESIGNATION VARCHAR(20),
    PRIMARY KEY (EMPLOYEE_ID, DEPARTMENT_ID),
    FOREIGN KEY (DESIGNATION) REFERENCES POST(DESIGNATION),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


-- (I) Write a before insert and before delete trigger on Employee table to
-- insert/update records in Department and Post table

DELIMITER //
CREATE TRIGGER INSERTION_UPDATE_DEPT_POST BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO DEPARTMENT(DEPARTMENT_ID) VALUES (NEW.DEPARTMENT_ID);
    INSERT INTO POST(DESIGNATION) VALUES (NEW.DESIGNATION);
END;
//
DELIMITER ;

-- 
